package com.kun.flow.data;

import com.kun.flow.bean.Pagination;
import com.kun.flow.model.News;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewsMapper extends IMapper<News> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    List<News>  listByCid(@Param("key") News cid, @Param("page") Pagination page);
    List<News>  getSummary();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    News selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByPrimaryKey(News record);
	
	/* @param cid
     * @throws Exception
     */
    public int getCountbyCid(@Param("key") News cid) throws Exception;
    public int getAuditCount() throws Exception;
}