package com.kun.flow.data;

import com.kun.flow.model.Operater;
import com.kun.flow.model.OperaterExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperaterMapper extends IMapper<Operater> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int countByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int deleteByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int insert(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int insertSelective(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    List<Operater> selectByExample(OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    Operater selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int updateByExampleSelective(@Param("record") Operater record, @Param("example") OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int updateByExample(@Param("record") Operater record, @Param("example") OperaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int updateByPrimaryKeySelective(Operater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPERATER
     *
     * @mbggenerated Wed Oct 29 22:00:16 CST 2014
     */
    int updateByPrimaryKey(Operater record);
}